@LibraryApi_HostAddress = http://localhost:5094

### admin token al
# @name adminLogin
POST {{LibraryApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@local",
  "password": "Admin123!"
}

### member token al
# @name memberLogin
POST {{LibraryApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "member@local",
  "password": "Member123!"
}


### tokensiz test(401 beklenir)
GET   {{LibraryApi_HostAddress}}/api/auth/test
Accept: application/json

### admin token ile test(200 beklenir)
GET   {{LibraryApi_HostAddress}}/api/auth/test
Accept: application/json
Authorization: Bearer {{adminLogin.response.body.accessToken}}

### staff-only Member token ile (403 beklenir)
GET {{LibraryApi_HostAddress}}/api/auth/staff-only
Authorization: Bearer {{memberLogin.response.body.accessToken}}

### Staff-only (admin token ile) (200 beklenir)
GET {{LibraryApi_HostAddress}}/api/auth/staff-only
Authorization: Bearer {{adminLogin.response.body.accessToken}}

### WhoAmI (admin token ile)
GET {{LibraryApi_HostAddress}}/api/auth/whoami
Authorization: Bearer {{adminLogin.response.body.accessToken}}

### WhoAmI (member token ile)
GET {{LibraryApi_HostAddress}}/api/auth/whoami
Authorization: Bearer {{memberLogin.response.body.accessToken}}